Control.Web/Models/Issue.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Control.Web.Models
{
    public class Issue
    {
        [Key]
        public int Id { get; set; }

        public required string Name { get; set; }

        public string? Description { get; set; }

        public IssueDiscipline Discipline { get; set; }

        public DateTime CreationDateTime { get; set; }

        public DateTime? CompletionDateTime { get; set; }

        public IssueStatus Status { get; set; }

        // Реляционные отношения
        public required int ProjectId { get; set; }

        [ForeignKey(nameof(ProjectId))]
        public Project? Project { get; set; }

        public string? CreatorId { get; set; }

        [ForeignKey(nameof(CreatorId))]
        public User? Creator { get; set; }

        public string? ExecutorId { get; set; }

        [ForeignKey(nameof(ExecutorId))]
        public User? Executor { get; set; }

        public List<IssueComment> IssueComments { get; set; } = new List<IssueComment>();
    }
}

Control.Web/Models/IssueViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Control.Web.Models
{
    public class IssueViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Наименование")]
        [Required(ErrorMessage = "Обязательное поле")]
        [DataType(DataType.Text)]
        [StringLength(500, MinimumLength = 2, ErrorMessage = "Наименование должно содержать от 2 до 500 символов")]
        public required string Name { get; set; }

        [Display(Name = "Описание")]
        [Required(ErrorMessage = "Обязательное поле")]
        [DataType(DataType.MultilineText)]
        [StringLength(500, MinimumLength = 2, ErrorMessage = "Описание должно содержать от 2 до 500 символов")]
        public string? Description { get; set; }

        [Display(Name = "Раздел")]
		[Required(ErrorMessage = "Обязательное поле")]
		public IssueDiscipline Discipline { get; set; }

        [Display(Name = "Статус")]
		[Required(ErrorMessage = "Обязательное поле")]
		public IssueStatus Status { get; set; }

        [Display(Name = "Проект")]
        [Required(ErrorMessage = "Обязательное поле")]
        public required int ProjectId { get; set; }

        [Display(Name = "Создатель")]
        public string? CreatorId { get; set; }

        [Display(Name = "Исполнитель")]
        public string? ExecutorId { get; set; }
    }
}

Control.Web/Controllers/IssuesController.cs
using Control.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Runtime.CompilerServices;

namespace Control.Web.Controllers
{
    public class IssuesController : Controller
    {
        private readonly IIssuesService _service;

		public IssuesController(IIssuesService service)
		{
			_service = service;
		}

		public IActionResult Index(int projectId)
        {
            var projectIssues = _service.GetIssuesByProjectId(projectId);

            // Для кнопки Добавить, так как невозможно получить имя проекта из любого замечания, если их еще нет в данном проекте.
            ViewBag.ProjectId = projectId;

			if (projectIssues == null)
            {
                return View("IssueNotFound");
            }

            return View(projectIssues);
        }

        public IActionResult Details(int projectId, int id)
        {
            var projectIssue = _service.GetIssueByProjectIdAndId(projectId, id);

            if (projectIssue == null)
            {
                return View("IssueNotFound");
            }

            return View(projectIssue);
        }

        public IActionResult Add(int projectId)
        {
            var dropdowns = _service.GetIssueDropdowns();
            ViewBag.Users = new SelectList(dropdowns.Users, "Id", "FullName");
            ViewBag.Projects = new SelectList(dropdowns.Projects, "Id", "Name");

            return View();
        }

        [HttpPost]
        public IActionResult Add(int projectId, IssueViewModel issueVM)
        {
            _service.AddIssue(projectId, issueVM);

            return RedirectToAction(nameof(Index), new { projectId });
        }

        public IActionResult Edit(int projectId, int id)
        {
            var issueDb = _service.GetIssueByProjectIdAndId(projectId, id);

			if (issueDb == null)
            {
                return View("IssueNotFound");
            }

            var issueVM = new IssueViewModel
            {
                Id = issueDb.Id,
                Name = issueDb.Name,
                Description = issueDb.Description,
                Status = issueDb.Status,
                Discipline = issueDb.Discipline,
                ProjectId = issueDb.ProjectId,
                CreatorId = issueDb.CreatorId,
                ExecutorId = issueDb.ExecutorId,
            };

            var dropdowns = _service.GetIssueDropdowns();
            ViewBag.Users = new SelectList(dropdowns.Users, "Id", "FullName");
			ViewBag.Projects = new SelectList(dropdowns.Projects, "Id", "Name");

			return View(issueVM);
        }

        [HttpPost]
        public IActionResult Edit(int projectId, int id, IssueViewModel issueVM)
        {
            var issueDb = _service.GetIssueByProjectIdAndId(projectId, id);

            if (issueDb == null)
            {
                return View("IssueNotFound");
            }

            _service.EditIssue(projectId, issueVM);

			return RedirectToAction(nameof(Index), new { projectId });
		}
	}
}

Control.Web/Views/Issues/Add.cshtml
@model IssueViewModel

@{
	ViewData["Title"] = "Новое замечание";
}

<div class="row">
	<div>
		<p>
			<h1>Новое замечание</h1>
		</p>

		<div class="row">
			<div class="col">
				<form asp-controller="Issues" asp-action="Add" method="post">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>

					<div class="row">
						<div class="col">
							<div class="form-group">
								<label asp-for="Discipline" class="control-label"></label>
								<select asp-for="Discipline" required class="form-control" asp-items="Html.GetEnumSelectList<IssueDiscipline>()"></select>
								<span asp-validation-for="Discipline" class="text-danger"></span>
							</div>

							<div class="form-group">
								<label asp-for="Name" class="control-label"></label>
								<input asp-for="Name" type="text" required minlength="2" maxlength="500" class="form-control" />
								<span asp-validation-for="Name" class="text-danger"></span>
							</div>

							<div class="form-group">
								<label asp-for="Description" class="control-label"></label>
								<textarea asp-for="Description" minlength="2" maxlength="500" class="form-control"></textarea>
								<span asp-validation-for="Description" class="text-danger"></span>
							</div>

							<div class="form-group">
								<label asp-for="ProjectId" class="control-label"></label>
								<select asp-for="ProjectId" required class="form-control" asp-items="ViewBag.Projects"></select>
								<span asp-validation-for="ProjectId" class="text-danger"></span>
							</div>

							<div class="form-group">
								<label asp-for="CreatorId" class="control-label"></label>
								<select asp-for="CreatorId" class="form-control" asp-items="ViewBag.Users"></select>
								<span asp-validation-for="CreatorId" class="text-danger"></span>
							</div>

							<div class="form-group">
								<label asp-for="ExecutorId" class="control-label"></label>
								<select asp-for="ExecutorId" class="form-control" asp-items="ViewBag.Users"></select>
								<span asp-validation-for="ExecutorId" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-outline-success" asp-controller="Issues" asp-action="Add">Добавить</button>
						<a class="btn btn-outline-primary" asp-controller="Issues" asp-action="Index">Назад</a>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

Control.Web/Views/Issues/Details.cshtml
@model Issue;

@{
    ViewData["Title"] = $"Замечание №{Model.Id}";
}

<div class="card" style="max-width: 100%">
    <div class="row">
        <div class="col">
            <div class="card-body">
                <h5 class="card-title">@Model.Name</h5>
                <p class="card-text">№@Model.Id</p>
                <p class="card-text">Проект: @Model.Project.Name</p>
                <p class="card-text">Описание: @Model.Description</p>
                <p class="card-text">Раздел: @EnumHelper.GetDisplayName(Model.Discipline)</p>
                <p class="card-text">Дата создания: @Model.CreationDateTime</p>

                @if (Model.Status == IssueStatus.Fixed)
                {
                    <p class="card-text">Дата отработки: @Model.CompletionDateTime</p>
                }

                <p class="card-text">Создатель: @Model.Creator.FullName</p>
                <p class="card-text">Исполнитель: @Model.Executor.FullName</p>

                @if (Model.Status == IssueStatus.Active)
                {
                    <p class="card-text">
                        Статус: <span class="badge bg-primary text-white">@EnumHelper.GetDisplayName(Model.Status)</span>
                    </p>
                }
                else if (Model.Status == IssueStatus.Fixed)
                {
                    <p class="card-text">
                        Статус: <span class="badge bg-success text-white">@EnumHelper.GetDisplayName(Model.Status)</span>
                    </p>
                }
                else if (Model.Status == IssueStatus.Suspended)
                {
                    <p class="card-text">
                        Статус: <span class="badge bg-secondary text-white">@EnumHelper.GetDisplayName(Model.Status)</span>
                    </p>
                }
                else
                {
                    <p class="card-text">
                        Статус: <span class="badge bg-success text-white">@EnumHelper.GetDisplayName(Model.Status)</span>
                    </p>
                }

                <div class="btn-group">
                    <a class="btn btn-outline-success" asp-controller="Issues" asp-action="Edit" asp-route-projectId="@Model.ProjectId" asp-route-id="@Model.Id">Редактировать</a>
                    <a class="btn btn-outline-primary" asp-controller="Issues" asp-action="Index" asp-route-projectId="@Model.ProjectId">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card" style="max-width: 100%">
    <div class="card-header">
        Комментарии
    </div>
    <div class="card-body">
        @if (Model.IssueComments != null && Model.IssueComments.Count > 0)
        {
            foreach (var comment in Model.IssueComments)
            {
                <small class="text-muted">@comment.User.FullName, @comment.Date</small>
                <p>@comment.Text</p>
                <hr />
            }
        }
        else
        {
            <p>По данному замечанию пока нет комментариев.</p>
        }
    </div>
    <form class="card-footer" asp-controller="IssueComments" asp-action="Add" method="post">
        <input type="hidden" name="IssueId" value="@Model.Id" />
        <div class="form-group">
            <label class="form-label">Комментарий:</label>
            <textarea class="form-control" name="Text" placeholder="Комментарий..."></textarea>
        </div>
        <br />
        <button type="submit" class="btn btn-outline-success" asp-controller="IssueComments" asp-action="Add" asp-route-projectId="@Model.ProjectId" asp-route-id="@Model.Id">Отправить</button>
    </form>      
</div>

Control.Web/Views/Issues/Edit.cshtml
@model IssueViewModel

@{
	ViewData["Title"] = "Редактирование замечания";
}

<div class="row">
	<div>
		<p>
			<h1>Редактирование замечания</h1>
		</p>

		<div class="row">
			<div class="col">
				<form asp-controller="Issues" asp-action="Edit" method="post">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>

					<div class="row">
						<div class="col">
							<div class="form-group">
								<label asp-for="Discipline" class="control-label"></label>
								<select asp-for="Discipline" required class="form-control" asp-items="Html.GetEnumSelectList<IssueDiscipline>()"></select>
								<span asp-validation-for="Discipline" class="text-danger"></span>
							</div>

							<div class="form-group">
								<label asp-for="Name" class="control-label"></label>
								<input asp-for="Name" required minlength="2" maxlength="500" type="text" class="form-control" />
								<span asp-validation-for="Name" class="text-danger"></span>
							</div>

							<div class="form-group">
								<label asp-for="Description" class="control-label"></label>
								<textarea asp-for="Description" minlength="2" maxlength="500" class="form-control"></textarea>
								<span asp-validation-for="Description" class="text-danger"></span>
							</div>

							<div class="form-group">
								<label asp-for="Status" class="control-label"></label>
								<select asp-for="Status" required class="form-control" asp-items="Html.GetEnumSelectList<IssueStatus>()"></select>
								<span asp-validation-for="Status" class="text-danger"></span>
							</div>

							<div class="form-group">
								<label asp-for="ProjectId" class="control-label"></label>
								<select asp-for="ProjectId" required class="form-control" asp-items="ViewBag.Projects"></select>
								<span asp-validation-for="ProjectId" class="text-danger"></span>
							</div>

							<div class="form-group">
								<label asp-for="CreatorId" class="control-label"></label>
								<select asp-for="CreatorId" class="form-control" asp-items="ViewBag.Users"></select>
								<span asp-validation-for="CreatorId" class="text-danger"></span>
							</div>

							<div class="form-group">
								<label asp-for="ExecutorId" class="control-label"></label>
								<select asp-for="ExecutorId" class="form-control" asp-items="ViewBag.Users"></select>
								<span asp-validation-for="ExecutorId" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-outline-success" asp-controller="Issues" asp-action="Edit" asp-route-projectId="@Model.ProjectId" asp-route-id="@Model.Id">Сохранить</button>
						<a class="btn btn-outline-primary" asp-controller="Issues" asp-action="Index" asp-route-projectId="@Model.ProjectId">Назад</a>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

Control.Web/Views/Issues/Index.cshtml
@model IEnumerable<Issue>;

@{
    ViewData["Title"] = "Замечания";
}

<a asp-controller="Issues" asp-action="Add" asp-route-projectId="@ViewBag.ProjectId" class="btn btn-outline-success">Добавить</a>
<div class="row">
    <h1>Замечания к проекту</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Дата создания</th>
                <th>Дата отработки</th>
                <th>Раздел</th>
                <th>Наименование</th>
                <th>Создатель</th>
                <th>Исполнитель</th>
                <th>Статус</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var issue in Model)
            {
                <tr>
                    <td>@issue.Id</td>
                    <td>@issue.CreationDateTime</td>
                    <td>@issue.CompletionDateTime</td>
                    <td>@EnumHelper.GetDisplayName(issue.Discipline)</td>
                    <td>@issue.Name</td>
                    @if (issue.Creator != null)
                    {
                        <td>@issue.Creator.FullName</td>
                    }
                    else
                    {
                        <td>
                            <span class="badge bg-danger text-white">Не назначен</span>
                        </td>
                    }

                    @if (issue.Executor != null)
                    {
                        <td>@issue.Executor.FullName</td>
                    }
                    else
                    {
                        <td>
                            <span class="badge bg-danger text-white">Не назначен</span>
                        </td>
                    }

                    @if (issue.Status == IssueStatus.Active)
                    {
                        <td class="card-text">
                            <span class="badge bg-primary text-white">@EnumHelper.GetDisplayName(issue.Status)</span>
                        </td>
                    }
                    else if (issue.Status == IssueStatus.Fixed)
                    {
                        <td class="card-text">
                            <span class="badge bg-success text-white">@EnumHelper.GetDisplayName(issue.Status)</span>
                        </td>
                    }
                    else if (issue.Status == IssueStatus.Suspended)
                    {
                        <td class="card-text">
                            <span class="badge bg-secondary text-white">@EnumHelper.GetDisplayName(issue.Status)</span>
                        </td>
                    }
                    else
                    {
                        <td class="card-text">
                            <span class="badge bg-success text-white">@EnumHelper.GetDisplayName(issue.Status)</span>
                        </td>
                    }

                    <td>
                        <a class="btn btn-outline-primary" asp-controller="Issues" asp-action="Details" asp-route-projectId="@issue.ProjectId" asp-route-id="@issue.Id">Подробнее</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<a class="btn btn-outline-primary" asp-controller="Projects" asp-action="Index">Назад</a>

Control.Web/Views/Issues/IssueNotFound.cshtml
Замечание(-я) не найдено(-ы)

Control.Web/Views/Issues/IssuesNotFound.cshtml
Замечание(-я) не найдено(-ы)